// Fish, rarities, descriptions, and locations

const rarityOrder = ["Common", "Uncommon", "Rare", "Mythical", "Legendary", "Unknown", "Extinct"];

const rarityWeights = {
      Common: 58,
      Uncommon: 25,
      Rare: 10,
      Mythical: 4.5,
      Legendary: 1.8,
      Unknown: 0.55,
      Extinct: 0.15
    };

const shakeCounts = {
      Common: 50,
      Uncommon: 45,
      Rare: 40,
      Mythical: 35,
      Legendary: 30,
      Unknown: 25,
      Extinct: 20
    };

const fishDescriptions = {
      "Trout":"A dependable waterfall fish with quick silver scales.",
      "Mullet":"A sturdy schooling fish that favors calmer edges of the basin.",
      "Largemouth Bass":"An aggressive freshwater hunter with an oversized mouth.",
      "Pike":"A long, sharp-toothed ambusher that strikes from submerged cover.",
      "Grouper":"A heavy-bodied fish that hides among deep waterfall rocks.",
      "Rubbish":"Waterlogged junk pulled from the current. Somehow, it still counts.",
      "Sockeye Salmon":"A determined red-sided salmon fighting against the waterfall flow.",
      "Clownfish":"A brightly striped visitor that looks very far from home.",
      "Angelfish":"A graceful fish whose fins drift like delicate banners.",
      "Anglerfish":"A gloomy deepwater oddity carrying its own glowing lure.",
      "Seahorse":"A tiny upright swimmer that curls its tail around river plants.",
      "Starfish":"A five-armed wanderer carried inland by Gravitas distortions.",
      "Tanglekelp":"A living knot of kelp that fights the line like a fish.",
      "Goldfish":"A gleaming ornamental fish made unusually valuable by the falls.",
      "Flounder":"A flat bottom-dweller with both eyes watching from one side.",
      "Reefrunner":"A swift mythical fish that leaves a streak of reef-colored light.",
      "Sawfish":"A powerful fish with a serrated snout built like a living blade.",
      "Catfish":"A massive whiskered legend that lurks beneath muddy ledges.",
      "Swordfish":"A legendary high-speed predator armed with a spear-like bill.",
      "Orbiting Orchidfish":"An impossible floral fish that circles the hook instead of swimming.",
      "Weird Algae":"A suspicious clump that pulses faintly beneath aurora light.",
      "Shark Egg":"A tough egg case with something restless moving inside.",
      "Red Snapper":"A bright red pond fish with a famously sharp bite.",
      "Lionfish":"A striped fish whose ornate spines warn careless anglers away.",
      "Squid":"A clever cephalopod that clouds the water when startled.",
      "Minnow":"A tiny, common-looking fish made uncommon by the pond's magic.",
      "Fresh Fertilizer":"A fragrant item catch that is unfortunately very fresh.",
      "Buried Treasure":"A mud-caked chest dragged from beneath the pond floor.",
      "Old Fishing Rod":"A retired rod that has apparently become somebody else's catch.",
      "Sunseeker":"A radiant fish that rises only while daylight touches the pond.",
      "Moonhider":"A pale fish that appears only after the sun has vanished.",
      "Blobfish":"A soft-bodied mythical fish that looks deeply unimpressed.",
      "Rainbow Snapper":"A daylight fish whose scales split sunlight into shifting colors.",
      "Skull":"A grim item catch polished smooth by years under the water.",
      "Phantom Fang":"A legendary spectral tooth that bites back through the line.",
      "Mosslurker":"An unknown moss-covered creature nearly indistinguishable from the bank.",
      "Coconut":"A baffling tropical item drifting in a decidedly non-tropical pond.",
      "Pufferfish":"A secretive round fish that inflates the moment it sees a hook.",
      "Dawn's Devil":"An extinct-looking horror that emerges only beneath dawn-colored light.",
      "Lunar Lurker":"An ancient nocturnal predator that can replace a Mosslurker encounter.",
      "Baby Manta":"A playful young ray that glides through the shoreline shallows.",
      "Dolphin":"A clever marine mammal that treats the fishing line like a game.",
      "Flying Fish":"A silver fish capable of bursting above the waves on winglike fins.",
      "Gallon Grouper":"An enormous grouper said to displace a gallon of water with every turn.",
      "Seagull":"An extremely confused bird that stole the bait and became the catch.",
      "Weird Parasite":"A twitching ocean parasite with no obvious preferred host.",
      "Mako Shark":"A streamlined shark famous for explosive speed.",
      "Coral Reef Shark":"A colorful reef hunter camouflaged among living coral.",
      "Sand Shark":"A bottom-hugging shark that erupts from the seabed.",
      "Lemon Shark":"A yellow-tinted coastal shark with a calm but powerful presence.",
      "Nurse Shark":"A broad-headed shark that searches the seafloor for prey.",
      "Baby Whale":"A curious young whale still small enough to challenge an angler.",
      "Krab":"A stubborn armored crustacean that insists its name is spelled with a K.",
      "Hammerhead Shark":"A legendary shark whose wide head senses movement across the shore.",
      "Megamouth Shark":"A rare deepwater giant with an enormous glowing mouth.",
      "Great White Shark":"The shore's legendary apex predator.",
      "Blue Whale":"The largest known animal, catchable only during Whale Abundance.",
      "Moby":"A scarred white whale that sometimes replaces a Blue Whale encounter.",
      "Mosasaurus":"An ancient marine reptile awakened by Shark Migration.",
      "Helipricon":"A prehistoric shark relative armed with a spiral tooth whorl.",
      "Megalodon":"An extinct super-shark whose capture completes Shark Shores.",
      "Godgazer":"An extinct eye-like creature that appears only beneath an eclipse.",
      "Kelpie":"A legendary water horse drawn from flooded shorelines.",
      "Kappa":"A legendary river spirit with a dangerous grip.",
      "Mermaid":"A legendary singer whose voice carries over floodwater.",
      "The Hydra":"An extinct many-headed monster awakened by extreme flooding.",
      "The Leviathan":"An extinct sea colossus too large for any ordinary waterway.",
      "Elder Kelpie":"An ancient Kelpie that sometimes replaces a younger one.",
      "Dissolved Bone":"A bone softened and scarred by acidic rain.",
      "Dissolved Fish":"A common fish partially eaten away by corrosive water.",
      "Skelefish":"A rare fish stripped almost completely to bone.",
      "Brinefish":"A rare acid-adapted fish covered in crystallized salt.",
      "Acid Dolphin":"A mythical dolphin glowing with corrosive energy.",
      "The Brine Phantom":"An unknown shape moving beneath acid-stained water.",
      "Dissolving Danger":"An extinct corrosive beast that seems to melt the water itself.",
      "Fried Fish":"A fish cooked by the heat before reaching the hook.",
      "Boiled Fish":"A fish boiled in drought-heated water.",
      "Roasted Fish":"A dried catch found where water used to be.",
      "Oiled Fish":"A slick fish cooked in naturally heated oil pools.",
      "Burnt Fish":"A charred catch barely recognizable as a fish.",
      "Skeletal Serpent":"An extinct serpent uncovered beneath a dried basin.",
      "Coral Piece":"A broken fragment from the Grand Reef.",
      "Clam":"A common shellfish sealed tightly against the current.",
      "Surgeonfish":"A common reef fish hiding among coral.",
      "Crab":"A stubborn crustacean clinging to the reef floor.",
      "Shrimp":"A tiny common reef scavenger.",
      "Wrasse":"An uncommon coral-dwelling fish with bright markings.",
      "Pearl":"A polished treasure found inside reef shells.",
      "Cleaner Wrasse":"An uncommon helper fish that lives inside coral.",
      "Bait Box":"A useful box lost by another angler.",
      "Damselfish":"An uncommon reef defender with surprising aggression.",
      "Jesterfish":"A rare coral fish with chaotic colors.",
      "Golden Trout":"A rare golden fish that somehow reached the reef.",
      "Mackerel":"A fast rare schooling fish.",
      "Butterflyfish":"A rare reef fish patterned like wings.",
      "Parrotfish":"A rare fish with a beak strong enough to bite coral.",
      "Orange Triggerfish":"A rare orange reef fish with a powerful jaw.",
      "Pale Tang":"A rare pale surgeonfish from deeper water.",
      "Blue Tang":"A rare blue reef fish with a sharp tail spine.",
      "Red Tang":"A rare red reef fish that guards coral territory.",
      "Rainbow Tang":"A mythical tang whose colors constantly shift.",
      "Chromis Damselfish":"A mythical damselfish glowing with reef energy.",
      "Prismize Goby":"A mythical goby that refracts light like glass.",
      "Toadfish":"A legendary ambush predator hiding beneath the reef.",
      "Translucent Seahorse":"A legendary seahorse nearly invisible in water.",
      "Manta Ray":"A legendary giant gliding above the reef.",
      "Venomfish":"A legendary reef predator carrying lethal venom.",
      "Reef Titan":"An unknown giant buried inside the reef.",
      "Grand Reef Titan":"An extinct titan that replaces a Reef Titan one time in ten.",
    };

const locations = {
      gravitas: {
        name:"The Gravitas Waterfall",
        desc:"A roaring basin where ordinary river fish drift beside things pulled in by impossible gravity.",
        fish:[
          ["Trout","Common",14],["Mullet","Common",12],["Largemouth Bass","Common",20],["Pike","Common",24],
          ["Grouper","Common",22],["Rubbish","Common",3,true],["Sockeye Salmon","Common",26],
          ["Clownfish","Uncommon",32],["Angelfish","Uncommon",38],["Anglerfish","Uncommon",45],
          ["Seahorse","Uncommon",50],["Starfish","Uncommon",42],["Tanglekelp","Rare",85],
          ["Goldfish","Rare",120],["Flounder","Rare",95],["Reefrunner","Mythical",260],
          ["Sawfish","Mythical",320],["Catfish","Mythical",240],["Swordfish","Legendary",750],
          ["Orbiting Orchidfish","Unknown",1800,false,"optional"]
        ]
      },
      aurora: {
        name:"Aurora Pond",
        desc:"A luminous pond where daylight and moonlight reveal entirely different creatures.",
        fish:[
          ["Weird Algae","Common",5,true],["Shark Egg","Common",35,true],["Red Snapper","Common",22],
          ["Lionfish","Common",28],["Squid","Uncommon",34],["Minnow","Uncommon",12],
          ["Fresh Fertilizer","Uncommon",18,true],["Buried Treasure","Rare",150,true],
          ["Old Fishing Rod","Rare",110,true],["Sunseeker","Rare",125,false,"day"],
          ["Moonhider","Rare",125,false,"night"],["Blobfish","Mythical",250],
          ["Rainbow Snapper","Mythical",340,false,"day"],["Skull","Mythical",190,true],
          ["Phantom Fang","Legendary",850],["Mosslurker","Unknown",1350,false,"optional"],
          ["Coconut","Unknown",500,true,"optional"],["Pufferfish","Unknown",900,false,"optional"],
          ["Dawn's Devil","Extinct",3500,false,"dayOptional"],["Lunar Lurker","Extinct",3200,false,"lunar"]
        ]
      },
      shark: {
        name:"Shark Shores",
        desc:"A dangerous coastline ruled by sharks, whales, prehistoric predators, and violent migrations.",
        fish:[
          ["Baby Manta","Uncommon",55],["Dolphin","Uncommon",90],["Flying Fish","Uncommon",62],
          ["Gallon Grouper","Rare",175],["Seagull","Rare",120,true],["Weird Parasite","Rare",155,true],
          ["Mako Shark","Mythical",420],["Coral Reef Shark","Mythical",390],["Sand Shark","Mythical",410],
          ["Lemon Shark","Mythical",440],["Nurse Shark","Mythical",400],["Baby Whale","Mythical",500],["Krab","Mythical",360],
          ["Hammerhead Shark","Legendary",1050],["Megamouth Shark","Legendary",1150],["Great White Shark","Legendary",1450],
          ["Blue Whale","Legendary",1800,false,"whale"],["Moby","Unknown",4500,false,"moby"],
          ["Mosasaurus","Unknown",6000,false,"migration"],["Helipricon","Unknown",5200,false,"migration"],
          ["Megalodon","Extinct",12000,false,"migrationRequired"]
        ]
      },

      grandreef:{
        name:"The Grand Reef",
        desc:"A massive living reef filled with coral tunnels, hidden fish, and ancient titans.",
        fish:[
          ["Coral Piece","Common",16,true],["Clam","Common",18],["Surgeonfish","Common",22,false,"coral"],
          ["Crab","Common",20],["Shrimp","Common",12],["Wrasse","Uncommon",38,false,"coral"],
          ["Pearl","Common",55,true],["Cleaner Wrasse","Uncommon",44,false,"coral"],
          ["Bait Box","Uncommon",48,true],["Damselfish","Uncommon",46],["Jesterfish","Rare",120,false,"coral"],
          ["Golden Trout","Rare",135],["Mackerel","Rare",105],["Butterflyfish","Rare",125],
          ["Parrotfish","Rare",145],["Orange Triggerfish","Rare",138],["Pale Tang","Rare",128],
          ["Blue Tang","Rare",132],["Red Tang","Rare",136],["Rainbow Tang","Mythical",360],
          ["Chromis Damselfish","Mythical",390],["Prismize Goby","Mythical",420],
          ["Toadfish","Legendary",850],["Translucent Seahorse","Legendary",900],
          ["Manta Ray","Legendary",980],["Venomfish","Legendary",1100],
          ["Reef Titan","Unknown",2600,false,"optional"],["Grand Reef Titan","Extinct",6200,false,"reefTitan"]
        ]
      },

    };
